# Generated by Django 2.2.6 on 2019-10-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteado', '0002_auto_20191013_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'M'), ('Feminino', 'F')], default=0, max_length=100, verbose_name='Sexo'),
            preserve_default=False,
        ),
    ]
